### ISSUE TITLE
i get error when try run app

### ISSUE THREAD

**Issue by AnasProgrammer2** [X-SLAYER/Flutter-Tiktok-UI-API-Clone#1]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/getflutter-1.1.3/lib/components/appbar/gf_appbar.dart:311:57: Error: No named parameter with the name 'nullOk'.
    final ScaffoldState scaffold = Scaffold.of(context, nullOk: true);
                                                        ^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scaffold.dart:1944:24: Context: Found this candidate, but the arguments don't match.
  static ScaffoldState of(BuildContext context) {
                       ^^
3

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991

**Comment by jntagadiad** [comment]
try changing the getflutter in pubspec into getwidget
